// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTQjtFPFGyU6GM3279-IS1RFYQUDDMtEE',
    appId: '1:663379053776:web:1b3cead135fec1108362d5',
    messagingSenderId: '663379053776',
    projectId: 'fcmln-31ba7',
    authDomain: 'fcmln-31ba7.firebaseapp.com',
    storageBucket: 'fcmln-31ba7.firebasestorage.app',
    measurementId: 'G-VKNDBM7EE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGE0QRXwbYBzwKvVJcErX4x_XntmCSsq0',
    appId: '1:663379053776:android:34cdfcdc5a1dc4b88362d5',
    messagingSenderId: '663379053776',
    projectId: 'fcmln-31ba7',
    storageBucket: 'fcmln-31ba7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu18crpO5C_X3Ydrp4ENsdDIuJCzmxMJw',
    appId: '1:663379053776:ios:6bca27ce37a4079f8362d5',
    messagingSenderId: '663379053776',
    projectId: 'fcmln-31ba7',
    storageBucket: 'fcmln-31ba7.firebasestorage.app',
    iosBundleId: 'com.example.testWorkVpn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu18crpO5C_X3Ydrp4ENsdDIuJCzmxMJw',
    appId: '1:663379053776:ios:6bca27ce37a4079f8362d5',
    messagingSenderId: '663379053776',
    projectId: 'fcmln-31ba7',
    storageBucket: 'fcmln-31ba7.firebasestorage.app',
    iosBundleId: 'com.example.testWorkVpn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTQjtFPFGyU6GM3279-IS1RFYQUDDMtEE',
    appId: '1:663379053776:web:771a84ce9ebb25828362d5',
    messagingSenderId: '663379053776',
    projectId: 'fcmln-31ba7',
    authDomain: 'fcmln-31ba7.firebaseapp.com',
    storageBucket: 'fcmln-31ba7.firebasestorage.app',
    measurementId: 'G-J6BDDNEJNV',
  );
}
